@startuml diagram_classes
left to right direction
class User {
    name: string
    firstname: string
    age: number
}
class Association {
    name: string
}
class Minute {
    date: string
    content: string
}
Minute "*" -- "1" Association
Minute "*" o-- "*" User: voters
User "*" -- "*" Association
@enduml